Data Encoding
1. Nominal / One Hot Encoding 
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

Nominal / one hot encoding

represent categorical data into numerical data 

disadvantages  : dont use when categories are more can cause overfitting
create sparse matrix can be confusing  : overfitting

1. red [1,0,0]
2. blue [0,1,0]
3. green [0,0,1]

In [38]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [39]:
df = pd.DataFrame({
    'color': ['red', 'orange', 'purple', 'green', 'blue']
})
df.head()

    color
0     red
1  orange
2  purple
3   green
4    blue

In [40]:
## Crete an instance of Onehotencoder

encoder = OneHotEncoder()

In [41]:
## perform fit and transform

encoded = encoder.fit_transform(df[['color']]).toarray()  ## doble bracket for color gives in rows and col value

In [42]:
import pandas as pd
encoded_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())  # automatic col names created

In [43]:
encoded_df

   color_blue  color_green  color_orange  color_purple  color_red
0         0.0          0.0           0.0           0.0        1.0
1         0.0          0.0           1.0           0.0        0.0
2         0.0          0.0           0.0           1.0        0.0
3         0.0          1.0           0.0           0.0        0.0
4         1.0          0.0           0.0           0.0        0.0

In [44]:
encoder.transform([['blue']]).toarray()   #check for single

c:\Users\PRACHI\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0., 0., 0.]])

USing Tips Data

In [57]:
## Using tips data

In [49]:
import seaborn as sns

df = sns.load_dataset('tips')
df                 ### convert this categorical variables sex, smoker, day, time to onehotencoder

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [50]:
df[['sex', 'smoker', 'day', 'time']]

        sex smoker   day    time
0    Female     No   Sun  Dinner
1      Male     No   Sun  Dinner
2      Male     No   Sun  Dinner
3      Male     No   Sun  Dinner
4    Female     No   Sun  Dinner
..      ...    ...   ...     ...
239    Male     No   Sat  Dinner
240  Female    Yes   Sat  Dinner
241    Male    Yes   Sat  Dinner
242    Male     No   Sat  Dinner
243  Female     No  Thur  Dinner

[244 rows x 4 columns]

In [51]:

from sklearn.preprocessing import OneHotEncoder

In [52]:
# create Instance

encoder = OneHotEncoder()

In [53]:
# perform fit_transform we can convert categories into variables

encoded = encoder.fit_transform(df[['sex']]).toarray()

In [ ]:
encoded

array([[1., 1.]])

In [54]:
## Create data frame to check the categories are encoded or not using pandas

In [55]:
import pandas as pd

encoded_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [56]:
encoded_df

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [58]:
## check only one value 

encoder.transform([['Female']]).toarray()

c:\Users\PRACHI\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0.]])