Target Guided Ordinal Encoding 

# it is a technique used to encode categorical variables based on their relationship with target variable 

# useful when we have a categorical variable with large number of unique categories

# we replace each categorical varizble with a numerical value based on the mean or median of the target variable for the category. 

# cretes monotonic relationshop between the categorical variables and target varibles

In [92]:
import pandas as pd

df = pd.DataFrame({
    'city': ['new york', 'london', 'paris', 'tokyo', 'new york', 'paris'],
    'price' : [200, 150, 300, 250, 180, 320]
})

In [93]:
df

       city  price
0  new york    200
1    london    150
2     paris    300
3     tokyo    250
4  new york    180
5     paris    320

##  based on group of city replace price with there mean or median

In [94]:
mean_price = df.groupby('city')['price'].mean().to_dict()
mean_price

{'london': 150.0, 'new york': 190.0, 'paris': 310.0, 'tokyo': 250.0}

In [95]:
df['city_encoded'] = df['city'].map(mean_price)    ## replaced with maped values

In [96]:
df

       city  price  city_encoded
0  new york    200         190.0
1    london    150         150.0
2     paris    300         310.0
3     tokyo    250         250.0
4  new york    180         190.0
5     paris    320         310.0

In [97]:
df[['city_encoded', 'price']]

   city_encoded  price
0         190.0    200
1         150.0    150
2         310.0    300
3         250.0    250
4         190.0    180
5         310.0    320

## Based on dataset tips  : covert the time based on total bill

In [98]:
import seaborn as sns
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [99]:
import pandas as pd
mean_totalbill = df.groupby('time')['total_bill'].mean()

mean_totalbill

C:\Users\PRACHI\AppData\Local\Temp\ipykernel_19044\1282538959.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_totalbill = df.groupby('time')['total_bill'].mean()

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [100]:
df['time_encoded'] = df['time'].map(mean_totalbill)
df

     total_bill   tip     sex smoker   day    time  size time_encoded
0         16.99  1.01  Female     No   Sun  Dinner     2    20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3    20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3    20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2    20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4    20.797159
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2    20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2    20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2    20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2    20.797159

[244 rows x 8 columns]

In [101]:
df[['time', 'time_encoded']]
df.head()

   total_bill   tip     sex smoker  day    time  size time_encoded
0       16.99  1.01  Female     No  Sun  Dinner     2    20.797159
1       10.34  1.66    Male     No  Sun  Dinner     3    20.797159
2       21.01  3.50    Male     No  Sun  Dinner     3    20.797159
3       23.68  3.31    Male     No  Sun  Dinner     2    20.797159
4       24.59  3.61  Female     No  Sun  Dinner     4    20.797159